services:
  smartfleet:
    image: smartfleet
    build:
      context: ./SmartFleet
      dockerfile: SmartFleet/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=ep-falling-rice-a8o5qfow-pooler.eastus2.azure.neon.tech; Database=neondb; Username=neondb_owner; Password=npg_sztdHA3W0UTv; SSL Mode=VerifyFull; Channel Binding=Require;
      TelemetryIngestion__Host: mosquitto
    ports:
      - "8080:8080"
    volumes:
      - smartfleet_uploads:/app/wwwroot/uploads
    restart: unless-stopped
    networks:
      - default
      - smartfleet_shared

volumes:
  smartfleet_uploads:

networks:
  smartfleet_shared:
    external: true
    name: smartfleet_shared
