services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: SmartFleet
      POSTGRES_USER: smartfleet
      POSTGRES_PASSWORD: smartfleet_pw
    ports:
      - "5432:5432"
    volumes:
      - smartfleet_pgdata:/var/lib/postgresql/data

  smartfleet:
    image: smartfleet
    build:
      context: .
      dockerfile: SmartFleet/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=ep-falling-rice-a8o5qfow-pooler.eastus2.azure.neon.tech; Database=neondb; Username=neondb_owner; Password=npg_sztdHA3W0UTv; SSL Mode=VerifyFull; Channel Binding=Require;
      TelemetryIngestion__Host: mosquitto
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - default
      - smartfleet_shared

volumes:
  smartfleet_pgdata:

networks:
  smartfleet_shared:
    external: true
    name: smartfleet_shared
