services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: SmartFleet
      POSTGRES_USER: smartfleet
      POSTGRES_PASSWORD: smartfleet_pw
    ports:
      - "5432:5432"
    volumes:
      - smartfleet_pgdata:/var/lib/postgresql/data

volumes:
  smartfleet_pgdata:
